### ISSUE TITLE
add bug to highlighted keywords

### ISSUE THREAD

**Issue by meddulla** [samsonw/vim-task#4]
I like to differentiate between normal tasks and tasks that are bugs in my notes so I added bug to the keywords list. Maybe others find it useful as well.

In task.vim change this

syntax keyword taskKeyword New new Working working Done done Todo TODO todo

to

syntax keyword taskKeyword New new Working working Done done Todo TODO todo bug Bug

Cheers,

Sofia

**Comment by samsonw** [comment]
Just commit the change, thanks.
